"""level_number_column_added_to_customer

Revision ID: 10aba2d95554
Revises: cf1f8fe17c34
Create Date: 2025-03-11 22:24:59.666860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10aba2d95554'
down_revision: Union[str, None] = 'cf1f8fe17c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_levels', sa.Column('level_number', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_levels', 'level_number')
    # ### end Alembic commands ###
