"""service_images_added

Revision ID: 3a1e3b1f3710
Revises: e0d28f29a2de
Create Date: 2025-01-31 14:46:09.991554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1e3b1f3710'
down_revision: Union[str, None] = 'e0d28f29a2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_images',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('image_link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_images')
    # ### end Alembic commands ###
