"""admin_comment_column_added_to_product_feedbacks

Revision ID: 60c51bc2b285
Revises: d1dc7ee19546
Create Date: 2025-03-06 11:48:34.337489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c51bc2b285'
down_revision: Union[str, None] = 'd1dc7ee19546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_feedbacks', sa.Column('admin_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_feedbacks', 'admin_comment')
    # ### end Alembic commands ###
