"""main_info_images added

Revision ID: 6bc3f51ca47e
Revises: 9aac096ff15b
Create Date: 2025-01-21 15:56:51.989000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc3f51ca47e'
down_revision: Union[str, None] = '9aac096ff15b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_info_images',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('image_link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_info_images')
    # ### end Alembic commands ###
