"""product_reviews_table_renamed_and_changed

Revision ID: 90715a0905a7
Revises: 9a5de1e0dd40
Create Date: 2025-02-07 13:31:43.365250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90715a0905a7'
down_revision: Union[str, None] = '9a5de1e0dd40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('liked_text', sa.String(), nullable=False),
    sa.Column('disliked_text', sa.String(), nullable=False),
    sa.Column('number_of_likes', sa.SmallInteger(), nullable=False),
    sa.Column('number_of_dislikes', sa.SmallInteger(), nullable=False),
    sa.Column('date_of_registration', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('date_of_update', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('product_reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_reviews',
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('number_of_likes', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('number_of_dislikes', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('date_of_registration', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('date_of_update', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='product_reviews_author_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='product_reviews_product_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('author_id', 'product_id', name='product_reviews_pkey')
    )
    op.drop_table('product_feedbacks')
    # ### end Alembic commands ###
