"""product_reviews_table_changed

Revision ID: 9a5de1e0dd40
Revises: 020b1aab1d64
Create Date: 2025-02-07 10:28:05.294685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5de1e0dd40'
down_revision: Union[str, None] = '020b1aab1d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_reviews', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('product_reviews', sa.Column('feedback_text', sa.String(), nullable=False))
    op.drop_column('product_reviews', 'review_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_reviews', sa.Column('review_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('product_reviews', 'feedback_text')
    op.drop_column('product_reviews', 'id')
    # ### end Alembic commands ###
