"""empty message

Revision ID: 9aac096ff15b
Revises: 
Create Date: 2025-01-20 22:43:34.385078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aac096ff15b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_levels',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('delivery_types',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('order_statuses',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('payment_methods',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('product_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), server_default='Новый', nullable=False),
    sa.Column('last_name', sa.String(length=50), server_default='Пользователь', nullable=False),
    sa.Column('phone_number', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('login', sa.String(length=30), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('solt', sa.String(), nullable=True),
    sa.Column('date_of_registration', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('date_of_update', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('bonus_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_level_name', sa.String(length=50), nullable=False),
    sa.Column('discount_amount_in_percent', sa.SmallInteger(), nullable=False),
    sa.Column('date_of_registration', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('date_of_update', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['customer_level_name'], ['customer_levels.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_subtypes',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_link', sa.String(), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['type_name'], ['product_types.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('street', sa.String(length=30), nullable=False),
    sa.Column('house_number', sa.String(length=10), nullable=False),
    sa.Column('entrance', sa.String(length=5), nullable=False),
    sa.Column('delivery_point', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_type_name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(length=50), nullable=False),
    sa.Column('payment_method_name', sa.String(length=50), nullable=False),
    sa.Column('date_of_registration', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('date_of_update', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['users_addresses.id'], ),
    sa.ForeignKeyConstraint(['delivery_type_name'], ['delivery_types.name'], ),
    sa.ForeignKeyConstraint(['payment_method_name'], ['payment_methods.name'], ),
    sa.ForeignKeyConstraint(['status_name'], ['order_statuses.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_link', sa.String(), nullable=False),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=True),
    sa.Column('product_subtype_name', sa.String(length=100), nullable=False),
    sa.Column('additional_information', sa.String(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=1, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['product_subtype_name'], ['product_subtypes.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('cart_items',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
    )
    op.create_table('order_items',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'product_id')
    )
    op.create_table('product_reviews',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.String(), nullable=False),
    sa.Column('number_of_likes', sa.SmallInteger(), nullable=False),
    sa.Column('number_of_dislikes', sa.SmallInteger(), nullable=False),
    sa.Column('date_of_registration', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('date_of_update', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('author_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_reviews')
    op.drop_table('order_items')
    op.drop_table('cart_items')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('users_addresses')
    op.drop_table('product_subtypes')
    op.drop_table('bonus_cards')
    op.drop_table('users')
    op.drop_table('product_types')
    op.drop_table('payment_methods')
    op.drop_table('order_statuses')
    op.drop_table('delivery_types')
    op.drop_table('customer_levels')
    # ### end Alembic commands ###
