"""multi_change

Revision ID: cf1f8fe17c34
Revises: 60c51bc2b285
Create Date: 2025-03-08 11:07:15.128392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1f8fe17c34'
down_revision: Union[str, None] = '60c51bc2b285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bonus_cards', 'customer_level_name',
               existing_type=sa.VARCHAR(length=50),
               server_default='Новичок',
               existing_nullable=False)
    op.drop_column('bonus_cards', 'discount_amount_in_percent')
    op.add_column('customer_levels', sa.Column('discount_amount_in_percent', sa.SmallInteger(), nullable=False))
    op.add_column('customer_levels', sa.Column('lower_threshold', sa.Integer(), nullable=False))
    op.alter_column('product_feedbacks', 'number_of_likes',
               existing_type=sa.SMALLINT(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('product_feedbacks', 'number_of_dislikes',
               existing_type=sa.SMALLINT(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.add_column('users', sa.Column('total_amount_of_purchases', sa.Float(), server_default=sa.text('0.0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_amount_of_purchases')
    op.alter_column('product_feedbacks', 'number_of_dislikes',
               existing_type=sa.SMALLINT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('product_feedbacks', 'number_of_likes',
               existing_type=sa.SMALLINT(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('customer_levels', 'lower_threshold')
    op.drop_column('customer_levels', 'discount_amount_in_percent')
    op.add_column('bonus_cards', sa.Column('discount_amount_in_percent', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.alter_column('bonus_cards', 'customer_level_name',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
