"""rating_column_type_changed_in_products

Revision ID: e0d28f29a2de
Revises: 84edf78775a7
Create Date: 2025-01-23 21:10:42.889779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d28f29a2de'
down_revision: Union[str, None] = '84edf78775a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
